CREATE TABLE paciente (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    nome VARCHAR(60) NOT NULL,
    sexo ENUM('masculino', 'feminino', 'nao_informado') NOT NULL,
    data_nascimento DATE NOT NULL,
    criado_em DATE DEFAULT (CURRENT_DATE) NOT NULL
);

CREATE TABLE usuario (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    nome VARCHAR(60) NOT NULL,
    matricula VARCHAR(10) NOT NULL UNIQUE,
    senha VARCHAR(60) NOT NULL,
    user_role ENUM('ADMIN', 'USER') NOT NULL,
    criado_em DATE DEFAULT (CURRENT_DATE) NOT NULL
);

CREATE TABLE anamnese (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    paciente_id INT NOT NULL,
    paciente_nome VARCHAR(60) NOT NULL,
    usuario_id INT NOT NULL,
    usuario_nome VARCHAR(60) NOT NULL,
    escolaridade ENUM('fundamental_completo', 'ensino_medio_completo', 'ensino_superior_incompleto', 'ensino_superior_completo', 'outra') NOT NULL,
    periodo_estudo ENUM('manha', 'tarde', 'noite', 'NA') NOT NULL,
    lanche_estudo BOOLEAN NOT NULL,
    periodo_trabalho ENUM('manha', 'tarde', 'noite', 'NA') NOT NULL,
    lanche_trabalho BOOLEAN NOT NULL,
    profissao VARCHAR(60),
    renda_familiar ENUM('menos_de_1_salario_minimo', 'de_1_a_2_salarios_minimos', 'de_3_a_5_salarios_minimos', 'mais_de_5_salarios_minimos', 'nao_sei') NOT NULL,
    num_pessoas_domicilio TINYINT NOT NULL,
    motivo TEXT NOT NULL,
    apresenta_doenca TEXT,
    antecedentes_familiares TEXT,
    medicamentos_continuos TEXT,
    suplementos_complementos TEXT,
    frequencia_evacuacao ENUM('diaria', 'alternada', 'tres_vezes_por_semana', 'menos_de_3_vezes_por_semana') NOT NULL,
    consistencia_evacuacao TINYINT NOT NULL,
    pratica_atv_fisica BOOLEAN NOT NULL,
    atv_fisica TEXT,
    cafe_da_manha TEXT,
    lanche_da_manha TEXT,
    almoco TEXT,
    lanche_da_tarde TEXT,
    jantar TEXT,
    ceia TEXT,
    legumes_cenoura ENUM('diario', 'semanal', 'mensal', 'nao'),
    legumes_beterraba ENUM('diario', 'semanal', 'mensal', 'nao'),
    legumes_berinjela ENUM('diario', 'semanal', 'mensal', 'nao'),
    legumes_pepino ENUM('diario', 'semanal', 'mensal', 'nao'),
    legumes_abobrinha ENUM('diario', 'semanal', 'mensal', 'nao'),
    legumes_chuchu ENUM('diario', 'semanal', 'mensal', 'nao'),
    legumes_tomate ENUM('diario', 'semanal', 'mensal', 'nao'),
    verduras_acelga ENUM('diario', 'semanal', 'mensal', 'nao'),
    verduras_agriao ENUM('diario', 'semanal', 'mensal', 'nao'),
    verduras_alface ENUM('diario', 'semanal', 'mensal', 'nao'),
    verduras_brocolis ENUM('diario', 'semanal', 'mensal', 'nao'),
    verduras_chicoria ENUM('diario', 'semanal', 'mensal', 'nao'),
    verduras_couve_manteiga ENUM('diario', 'semanal', 'mensal', 'nao'),
    verduras_couve_flor ENUM('diario', 'semanal', 'mensal', 'nao'),
    verduras_espinafre ENUM('diario', 'semanal', 'mensal', 'nao'),
    verduras_rucula ENUM('diario', 'semanal', 'mensal', 'nao'),
    frutas_c_laranja ENUM('diario', 'semanal', 'mensal', 'nao'),
    frutas_c_tangerina ENUM('diario', 'semanal', 'mensal', 'nao'),
    frutas_c_limao ENUM('diario', 'semanal', 'mensal', 'nao'),
    frutas_c_abacaxi ENUM('diario', 'semanal', 'mensal', 'nao'),
    frutas_c_acerola ENUM('diario', 'semanal', 'mensal', 'nao'),
    frutas_c_morango ENUM('diario', 'semanal', 'mensal', 'nao'),
    frutas_c_kiwi ENUM('diario', 'semanal', 'mensal', 'nao'),
    frutas_c_maracuja ENUM('diario', 'semanal', 'mensal', 'nao'),
    demais_frutas_banana ENUM('diario', 'semanal', 'mensal', 'nao'),
    demais_frutas_goiaba ENUM('diario', 'semanal', 'mensal', 'nao'),
    demais_frutas_maca ENUM('diario', 'semanal', 'mensal', 'nao'),
    demais_frutas_mamao ENUM('diario', 'semanal', 'mensal', 'nao'),
    demais_frutas_manga ENUM('diario', 'semanal', 'mensal', 'nao'),
    demais_frutas_melancia ENUM('diario', 'semanal', 'mensal', 'nao'),
    demais_frutas_melao ENUM('diario', 'semanal', 'mensal', 'nao'),
    demais_frutas_pera ENUM('diario', 'semanal', 'mensal', 'nao'),
    demais_frutas_pessego ENUM('diario', 'semanal', 'mensal', 'nao'),
    demais_frutas_uva ENUM('diario', 'semanal', 'mensal', 'nao'),
    leguminosas_feijao ENUM('diario', 'semanal', 'mensal', 'nao'),
    leguminosas_lentilha ENUM('diario', 'semanal', 'mensal', 'nao'),
    leguminosas_ervilha ENUM('diario', 'semanal', 'mensal', 'nao'),
    leguminosas_soja ENUM('diario', 'semanal', 'mensal', 'nao'),
    leguminosas_grao_de_bico ENUM('diario', 'semanal', 'mensal', 'nao'),
    leguminosas_vagem ENUM('diario', 'semanal', 'mensal', 'nao'),
    carnes_bovina ENUM('diario', 'semanal', 'mensal', 'nao'),
    carnes_suina ENUM('diario', 'semanal', 'mensal', 'nao'),
    carnes_aves ENUM('diario', 'semanal', 'mensal', 'nao'),
    carnes_peixe ENUM('diario', 'semanal', 'mensal', 'nao'),
    frutos_do_mar ENUM('diario', 'semanal', 'mensal', 'nao'),
    ovo ENUM('diario', 'semanal', 'mensal', 'nao'),
    arroz_branco_polido ENUM('diario', 'semanal', 'mensal', 'nao'),
    arroz_integral ENUM('diario', 'semanal', 'mensal', 'nao'),
    lacteos_leite_integral_desnatado_semi ENUM('diario', 'semanal', 'mensal', 'nao'),
    lacteos_leite_sem_lactose ENUM('diario', 'semanal', 'mensal', 'nao'),
    lacteos_queijos ENUM('diario', 'semanal', 'mensal', 'nao'),
    lacteos_iogurtes ENUM('diario', 'semanal', 'mensal', 'nao'),
    cereais_aveia ENUM('diario', 'semanal', 'mensal', 'nao'),
    cereais_granola_in_natura ENUM('diario', 'semanal', 'mensal', 'nao'),
    cereais_quinoa ENUM('diario', 'semanal', 'mensal', 'nao'),
    cereais_linhaca ENUM('diario', 'semanal', 'mensal', 'nao'),
    cereais_chia ENUM('diario', 'semanal', 'mensal', 'nao'),
    paes_frances_media_normal ENUM('diario', 'semanal', 'mensal', 'nao'),
    paes_frances_media_integral ENUM('diario', 'semanal', 'mensal', 'nao'),
    paes_forma ENUM('diario', 'semanal', 'mensal', 'nao'),
    paes_forma_integral ENUM('diario', 'semanal', 'mensal', 'nao'),
    paes_cara ENUM('diario', 'semanal', 'mensal', 'nao'),
    pastas_requeijao ENUM('diario', 'semanal', 'mensal', 'nao'),
    pastas_margarina ENUM('diario', 'semanal', 'mensal', 'nao'),
    pastas_manteiga ENUM('diario', 'semanal', 'mensal', 'nao'),
    pastas_ricota ENUM('diario', 'semanal', 'mensal', 'nao'),
    pastas_cottage ENUM('diario', 'semanal', 'mensal', 'nao'),
    pastas_doce_de_leite ENUM('diario', 'semanal', 'mensal', 'nao'),
    pastas_creme_de_avela ENUM('diario', 'semanal', 'mensal', 'nao'),
    pastas_geleia ENUM('diario', 'semanal', 'mensal', 'nao'),
    salgados_mistinho_esfiha ENUM('diario', 'semanal', 'mensal', 'nao'),
    salgados_coxinha_croquete ENUM('diario', 'semanal', 'mensal', 'nao'),
    salgados_empadas ENUM('diario', 'semanal', 'mensal', 'nao'),
    salgados_pao_de_queijo ENUM('diario', 'semanal', 'mensal', 'nao'),
    ultraprocessados_salgadinho_de_pacote ENUM('diario', 'semanal', 'mensal', 'nao'),
    ultraprocessados_biscoito_salgado ENUM('diario', 'semanal', 'mensal', 'nao'),
    ultraprocessados_biscoito_doce ENUM('diario', 'semanal', 'mensal', 'nao'),
    ultraprocessados_chocolate ENUM('diario', 'semanal', 'mensal', 'nao'),
    ultraprocessados_refrigerante ENUM('diario', 'semanal', 'mensal', 'nao'),
    ultraprocessados_suco_em_po_caixinha ENUM('diario', 'semanal', 'mensal', 'nao'),
    ultraprocessados_pratos_prontos_congelados ENUM('diario', 'semanal', 'mensal', 'nao'),
    ultraprocessados_macarrao_instantaneo ENUM('diario', 'semanal', 'mensal', 'nao'),
    ultraprocessados_bolinho ENUM('diario', 'semanal', 'mensal', 'nao'),
    ultraprocessados_fast_food ENUM('diario', 'semanal', 'mensal', 'nao'),
    embutidos_salame ENUM('diario', 'semanal', 'mensal', 'nao'),
    embutidos_presunto ENUM('diario', 'semanal', 'mensal', 'nao'),
    embutidos_apresuntado_mortadela ENUM('diario', 'semanal', 'mensal', 'nao'),
    embutidos_linguica_toscana_calabresa ENUM('diario', 'semanal', 'mensal', 'nao'),
    embutidos_salsicha ENUM('diario', 'semanal', 'mensal', 'nao'),
    embutidos_peito_de_peru ENUM('diario', 'semanal', 'mensal', 'nao'),
    embutidos_rosbife ENUM('diario', 'semanal', 'mensal', 'nao'),
    embutidos_nuggets ENUM('diario', 'semanal', 'mensal', 'nao'),
    embutidos_hamburguer_tradicional ENUM('diario', 'semanal', 'mensal', 'nao'),
    acucares_acucar ENUM('diario', 'semanal', 'mensal', 'nao'),
    acucares_adocante ENUM('diario', 'semanal', 'mensal', 'nao'),
    acucares_mel_melado ENUM('diario', 'semanal', 'mensal', 'nao'),
    acucares_produtos_confeitaria ENUM('diario', 'semanal', 'mensal', 'nao'),
    acucares_guloseimas ENUM('diario', 'semanal', 'mensal', 'nao'),
    acucares_achocolatados ENUM('diario', 'semanal', 'mensal', 'nao'),
    molhos_ketchup ENUM('diario', 'semanal', 'mensal', 'nao'),
    molhos_mostarda ENUM('diario', 'semanal', 'mensal', 'nao'),
    molhos_shoyu ENUM('diario', 'semanal', 'mensal', 'nao'),
    molhos_tare ENUM('diario', 'semanal', 'mensal', 'nao'),
    molhos_maionese ENUM('diario', 'semanal', 'mensal', 'nao'),
    quem_cozinha TEXT,
    necessidade_comer_estressado_ansioso_triste ENUM('sim', 'nao', 'as_vezes'),
    realiza_refeicoes_sozinho_acompanhado ENUM('sozinho', 'acompanhado'),
    excesso_alimentos_nao_saudaveis_sintomas TEXT,
    dificuldade_rotina_alimentar_saudavel TEXT,
    necessidade_consolo_alimentar ENUM('sim', 'nao', 'as_vezes'),
    dificuldade_parar_de_comer ENUM('sim', 'nao', 'as_vezes'),
    frequencia_fome_fisiologica VARCHAR(60),
    frequencia_necessidade_emocional_comer VARCHAR(60),
    nao_modificar_plano_alimentar TEXT,
    aversao_alimentar TEXT,
    tolera_alimentos_proteina_animal TEXT,
    alergia_intolerancias_alimentares TEXT,
    nota_saciedade_pos_refeicoes TINYINT NOT NULL,
    nota_humor_pos_refeicoes TINYINT NOT NULL,
    peso_atual FLOAT,
    estatura FLOAT,
    imc FLOAT,
    cb FLOAT,
    dct FLOAT,
    dcb FLOAT,
    dcse FLOAT,
    dcsi FLOAT,
    somatoria_4_dobras FLOAT,
    porcentagem_gordura_corporal_somatoria_4_dobras FLOAT,
    peso_gordura FLOAT,
    peso_massa_magra FLOAT,
    total_agua FLOAT,
    resistencia FLOAT,
    reactancia FLOAT,
    angulo_de_fase FLOAT,
    circunferencia_cintura FLOAT,
    circunferencia_quadril FLOAT,
    circunferencia_panturrilha FLOAT,
    porcentagem_agua_massa_magra FLOAT,
    emap_direita FLOAT,
    emap_esquerda FLOAT,
    forca_preencao_manual_direita INT,
    forca_preencao_manual_esquerda INT,
    metas TEXT,
    criado_em DATE DEFAULT (CURRENT_DATE) NOT NULL,
    FOREIGN KEY (paciente_id) REFERENCES paciente(id),
    FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

INSERT INTO usuario (nome, matricula, senha, user_role)
VALUES ('admin', 'admin', '$2a$12$nYYxMYVyQirARNSQBGLGOuVq7HAZkS9rJh7JmvUnKldrBkH1aFlSe', 'ADMIN');
